import "@/src/styles/globals.css";
import { AuthProvider } from "@/src/AuthProvider";
import { routing } from "@/src/i18n/routing";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { Cairo } from "next/font/google";
import { notFound } from "next/navigation";
import { Toaster } from "react-hot-toast";

const cairo = Cairo({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      dir={locale === "en" ? "ltr" : "rtl"}
      data-layout-dir={locale === "en" ? "ltr" : "rtl"}
      data-preloader="disable"
      suppressHydrationWarning
    >
      <body
        dir={locale === "en" ? "ltf" : "rtl"}
        className={`${cairo.className} flex flex-col min-h-screen [&>main]:flex-1`}
      >
        <NextIntlClientProvider>
          <Toaster
            position="top-center"
            reverseOrder={false}
            // gutter={8}
            containerClassName=""
            containerStyle={{}}
            toasterId="default"
            toastOptions={{
              // Define default options
              className: "",
              duration: 5000,
              removeDelay: 1000,
              style: {
                background: "#363636",
                color: "#fff",
                padding: "16px 24px",
              },
              loading: {
                duration: 2000,
                icon: "⏳",
                position: "top-center",
              },
              error: {
                duration: 1000,
                icon: "❌",
                position: "bottom-right",
              },

              // Default options for specific types
              success: {
                duration: 3000,
              },
            }}
          />
          <AuthProvider>
            <main>{children}</main>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
